[phases.setup]
nixPkgs = [
    "python39",
    "python39Packages.pip",
    "chromium",
    "libnss",
    "atk",
    "at-spi2-atk",
    "cups",
    "libdrm",
    "libxkbcommon",
    "libXcomposite",
    "libXdamage",
    "libXfixes",
    "libxrandr",
    "libgbm",
    "nss",
    "nspr",
    "dbus"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "playwright install --with-deps",
    "playwright install-deps"
]

[phases.build]
cmds = [
    "chmod +x start.sh"
]

[start]
cmd = "./start.sh"

[build.environment]
NIXPKGS_ALLOW_UNFREE = "1"
PLAYWRIGHT_BROWSERS_PATH = "0"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "0"
PYTHONUNBUFFERED = "true"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONFAULTHANDLER = "1"
PYTHONHASHSEED = "random"
PYTHONPATH = "/app"

[build.args]
NIXPKGS_ALLOW_UNFREE = "1"

[build.publish]
directories = [
    "/app/data",
    "/app/venues_data.json",
    "/app/venues_data.xlsx",
    "/app/progress.json"
]