[phases.setup]
nixPkgs = [
    "python39",
    "python39Packages.pip",
    "chromium",
    "libnss",
    "atk",
    "at-spi2-atk",
    "cups",
    "libdrm",
    "libxkbcommon",
    "libXcomposite",
    "libXdamage",
    "libXfixes",
    "libxrandr",
    "libgbm",
    "pango",
    "cairo",
    "alsa-lib",
    "at-spi2-core",
    "libxshmfence",
    "nss",
    "nspr",
    "dbus"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "playwright install chromium",
    "playwright install-deps"
]

[phases.build]
cmds = [
    "echo 'Building...'"
]

[start]
cmd = "./start.sh"