[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m playwright install chromium && python app.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = 8080
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = 0