[build]
builder = "nixpacks"

[deploy]
# Remove startCommand to use Procfile instead
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[build.uses]
before = "python -m playwright install chromium"

[env]
PORT = "8080"
PYTHONUNBUFFERED = "true"
PLAYWRIGHT_BROWSERS_PATH = "0"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = 0
NIXPKGS_ALLOW_UNFREE=1